apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: clickhouse-prod
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - ../../../base/clickhouse

namespace: clickhouse

commonLabels:
  environment: prod
  app.kubernetes.io/instance: clickhouse-prod

patchesStrategicMerge:
  - replica-patch.yaml
  - resource-patch.yaml
  - monitoring-patch.yaml

configMapGenerator:
  - name: clickhouse-prod-config
    literals:
      - log_level=warning
      - enable_query_log=false
      - enable_monitoring=true