apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8123"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: clickhouse
        env:
        - name: CLICKHOUSE_ENABLE_METRICS
          value: "true"
        - name: CLICKHOUSE_METRICS_PORT
          value: "8123"
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3