apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cilium-prod
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - ../../../base/cilium

namespace: kube-system

labels:
  - pairs:
      environment: prod
      app.kubernetes.io/instance: cilium-prod

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cilium-config
        namespace: kube-system
      data:
        debug: "false"
        log-level: "warn"
        enable-debug: "false"
        policy-enforcement: "always"
        enable-policy: "always"
        hubble-metrics: "dns,drop,tcp,flow"
    target:
      kind: ConfigMap
      name: cilium-config
  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: cilium
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
            - name: cilium-agent
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
                  cpu: "1000m"
    target:
      kind: DaemonSet
      name: cilium