apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: homelab-root
  labels:
    app.kubernetes.io/name: homelab
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: root

# Root-level kustomization for the entire homelab infrastructure
# This allows for easy deployment of the complete stack

# Infrastructure components (deploy first)
resources:
  - infrastructure/overlays/prod

# Application deployments (deploy after infrastructure)
components:
  - applications/overlays/prod

# Common labels applied to all resources
commonLabels:
  environment: homelab
  managed-by: kustomize
  project: homelab-devsecops

# Common annotations
commonAnnotations:
  deployment.kubernetes.io/managed-by: kustomize
  homelab.io/version: "1.0.0"
  homelab.io/deployment-date: "2024-01-01"

# Namespace prefix (optional)
# namespace: homelab

# Resource ordering - ensure infrastructure deploys before applications
# This is handled by separating infrastructure and applications