apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-base
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

namespace: argocd

commonLabels:
  app.kubernetes.io/name: argocd
  app.kubernetes.io/part-of: homelab-infrastructure

patchesStrategicMerge:
  - security-context.yaml
  - resource-limits.yaml