apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  template:
    spec:
      containers:
      - name: clickhouse
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
            ephemeral-storage: "512Mi"
          limits:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-data
  namespace: clickhouse
spec:
  resources:
    requests:
      storage: 5Gi