apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: auth
  labels:
    app: dex
    component: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
        component: auth
    spec:
      serviceAccountName: dex
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: dex
        image: ghcr.io/dexidp/dex:v2.38.0
        ports:
        - name: http
          containerPort: 5556
          protocol: TCP
        - name: grpc
          containerPort: 5557
          protocol: TCP
        command:
        - /usr/local/bin/dex
        - serve
        - /etc/dex/cfg/config.yaml
        env:
        - name: DEX_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dex-secrets
              key: DEX_ADMIN_PASSWORD
        - name: DEX_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dex-secrets
              key: DEX_USER_PASSWORD
        - name: DEX_OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: dex-secrets
              key: DEX_OAUTH2_PROXY_CLIENT_SECRET
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 5556
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 5556
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: dex
          items:
          - key: config.yaml
            path: config.yaml