apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: auth
  labels:
    app: dex
    component: auth
spec:
  selector:
    app: dex
  ports:
  - name: http
    port: 5556
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 5557
    targetPort: grpc
    protocol: TCP