apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-dev
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/environment: dev

resources:
  - ../../../base/argocd

commonLabels:
  environment: dev
  
patchesStrategicMerge:
  - replica-patch.yaml