apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: clickhouse
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: homelab-applications
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/component: database
  ports:
  - name: http
    port: 8123
    targetPort: http
    protocol: TCP
  - name: native
    port: 9000
    targetPort: native
    protocol: TCP
  - name: mysql
    port: 9004
    targetPort: mysql
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-headless
  namespace: clickhouse
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: homelab-applications
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/component: database
  ports:
  - name: http
    port: 8123
    targetPort: http
    protocol: TCP
  - name: native
    port: 9000
    targetPort: native
    protocol: TCP
  - name: mysql
    port: 9004
    targetPort: mysql
    protocol: TCP