apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-prod
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/environment: prod

resources:
  - ../../../base/argocd

commonLabels:
  environment: prod
  
patchesStrategicMerge:
  - replica-patch.yaml
  - resource-patch.yaml