apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnpg-controller-manager
  namespace: cnpg-system
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: ENABLE_LEADER_ELECTION
          value: "true"
        - name: CONTROLLER_MAX_CONCURRENT_RECONCILES
          value: "5"