apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: prometheus-base
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

namespace: monitoring

commonLabels:
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/part-of: homelab-applications