apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: pgadmin
type: Opaque
data:
  # Default credentials (change these in production)
  # email: admin@example.com (base64 encoded)
  email: YWRtaW5AZXhhbXBsZS5jb20=
  # password: changeme123 (base64 encoded)
  password: Y2hhbmdlbWUxMjM=