apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: homelab-infrastructure
  labels:
    app.kubernetes.io/name: homelab-infrastructure
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: infrastructure

# Infrastructure components kustomization
# Deploy these before applications

resources:
  - overlays/prod

# Common labels for all infrastructure components
commonLabels:
  tier: infrastructure
  environment: homelab
  managed-by: kustomize

# Common annotations
commonAnnotations:
  deployment.kubernetes.io/managed-by: kustomize
  homelab.io/tier: infrastructure