apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cilium-staging
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - ../../../base/cilium

namespace: kube-system

commonLabels:
  environment: staging
  app.kubernetes.io/instance: cilium-staging