apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: homelab-applications
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  # admin-user: admin (base64 encoded)
  admin-user: YWRtaW4=
  # admin-password: admin123! (base64 encoded)
  admin-password: YWRtaW4xMjMh